### ISSUE TITLE
AWS de path hatası

### ISSUE THREAD

**Issue by ttiras** [iyzico/iyzipay-node#102]
digital ocean da sorunsuz çalışan kod aws lambda da hata veriyor. 

Sanırım _initResources function ı  path yapısı farklı olduğu için resources a ulaşamıyor. 

`{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: ENOENT: no such file or directory, scandir '/var/task/resources'","reason":{"errorType":"Error","errorMessage":"ENOENT: no such file or directory, scandir '/var/task/resources'","code":"ENOENT","errno":-2,"syscall":"scandir","path":"/var/task/resources","stack":["Error: ENOENT: no such file or directory, scandir '/var/task/resources'","    at Object.readdirSync (fs.js:1047:3)","    at W._initResources (/var/task/lambda.js:51:7731)","    at new W (/var/task/lambda.js:51:7637)","    at xh (/var/task/lambda.js💯16777)","    at Ia.handle_request (/var/task/lambda.js:28:3673)","    at s (/var/task/lambda.js:28:5676)","    at s (/var/task/lambda.js:28:5643)","    at s (/var/task/lambda.js:28:5643)","    at s (/var/task/lambda.js:28:5643)","    at s (/var/task/lambda.js:28:5643)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: ENOENT: no such file or directory, scandir '/var/task/resources'","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:400:28)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:96:32)"]}`

**Comment by emrecoban** [comment]
Aynı sorunu ben de localimde yaşıyorum. Kendilerine e-posta ile sorunu ilettim. Eğer bir çözüm önerisi alamazsam üyeliğimi iptal ettireceğim.

**Comment by ttiras** [comment]
bilgi için teşekkürler. ben de pages klasöründe çalıştırıyorum ama bu klasöre destek birkaç yıl içinde sona erdiğinde, iyzipay-node bir 7 yıl daha güncellenmezse kullanamayabiliriz  :). AWS üzerindeki modern servislerin path yapısı sebebiyle hiçbirisinde çalışmıyor.

**Comment by ondery** [comment]
birkaç yıl değil, Next.js'de App Router yapısını kullanan biri olarak çoktan bu kütüphanenin kullanımı imkansız hale gelmiş bile :(

**Comment by serkancagman** [comment]
App Router ile kullanmak imkansız. [](https://github.com/iyzico/iyzipay-node/issues/113) arkadaş burada nextjs içerisinde pages ve app router ı birlikte kullanarak sorunu çözebileceğimiz anlatmış fakat app router dan pages router da bulunan api a istek atamıyorsun
